name: Build PR Documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - "kernels/**"
      - ".github/workflows/build_pr_documentation.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@e60a538eea9817ab312196d0d233604b01697265  # main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package_path: kernels/kernels/
      package: kernels
      version_tag_suffix: "kernels/src/"
